site_name: FiveM Loading Screen
site_url: https://fivem-loading.vercel.app/
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Getting Started: setup.md
  - Customization:
    - ğŸ¨ Overview: customization.md
    - ğŸ·ï¸ Watermark: watermark.md
    - ğŸ§· Social Headers: socials.md
    - ğŸ“œ Rules Panel: rules.md
    - Team Panel: team.md
    - Gallery Grid: gallery.md
    - Keyboard Overlay: keyboard-overlay.md
    - Music Player: music-player.md
  - Keyboard Overlay: keyboard-overlay.md
  - Video Background: video-background.md
  - FAQ: faq.md
  - Changelog: changelog.md
extra_css:
  - stylesheets/custom-admonitions.css
